Repository CSI-SCT-SB/EST102_Programming-in-C-S2-, pull requests merged in 2022-10, with the labels that each got.

#3 Add files via upload
  _11.linearsearch.c
Labels: hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#5 _3.ExpressionEvaluation.c
  _3.ExpressionEvaluation.c
  _4a.sumavg.c
  _4c.bubblesort.c
  _5b.concatenate.c
Labels: good first issue, hacktoberfest-accepted, Hero-of-the-day

#4 Add files via upload
  _16(b)bubblesort.c
Labels: good first issue, hacktoberfest-accepted

#7 Create _3.armstrong.c
  _3.armstrong.c
Labels: hacktoberfest-accepted

#9 _6.1.a.factorialwithrecur.c
  _6.1.a.factorialwithrecur.c
Labels: hacktoberfest-accepted

#8 new programs added
  _2a.largestnumber.c
  _2b.prime.c
  _5a.palindrome.c
  _5c.vowel.c
  _6.1.b.factorialwithoutrecur.c
  _6b.stringreversal.c
  _6c.matrixoperations.c
  _7a.euclidean.c
  _7b.employee.c
Labels: hacktoberfest-accepted

#10 codes
  _7c.union.c
  _8a.1.pointersum.c
  _8a.2.pointerswap.c
  _8b.pointerarray.c
  _8c.pointerarraysum.c
  _9.1.ab.filewriteread.c
  _9c.fileappend.c
  _9d.characwordline.c
Labels: good first issue, hacktoberfest-accepted

#12 added list of experiments
  Experiment_List.txt
Labels: hacktoberfest-accepted

#13 palindrome
  _10.palindrome.c
  _17.stringreversal.c
Labels: hacktoberfest-accepted

#14 Created _18.SpacesString.c
  _18.SpacesString.c
Labels: hacktoberfest-accepted

#16 Create _15(b).check_diagonal_matrix
  _15(b).check_diagonal_matrix
Labels: hacktoberfest-accepted

#15 Add files via upload
  _16(a).concatenate.c
  _18(b).struct_stdent_details.c
Labels: good first issue, hacktoberfest-accepted

#18 Add files via upload
  _15(b).check_diagonal_matrix.c
Labels: hacktoberfest-accepted

#19 s2
  factorial using recursion
  fibonacci series
  fibonacci series using recurssion
Labels: hacktoberfest-accepted

#23 Updation on Readme file of C pgrm repos
  README.md
Labels: hacktoberfest-accepted
